### ISSUE TITLE
converting torch7 model to coreml

### ISSUE THREAD

**Issue by engahmed1190** [torch/torch7#1077]
I have tried the coreml conversation on this repository:- [link](https://github.com/DmitryUlyanov/texture_nets ) 
they provide a pre-trained model:- [model.t7](https://yadi.sk/d/GwL9jNJovBwQg)

using the library torch2coreml 
This is the conversation method they provide [_torch_converter.py](https://github.com/prisma-ai/torch2coreml/blob/master/torch2coreml/_torch_converter.py)

this the basic code for conversation support instance normalization [conversation code sample](https://github.com/prisma-ai/torch2coreml/blob/master/example/fast-neural-style/convert-fast-neural-style.py)

getting this error

```
Traceback (most recent call last):
  File "convert-fast-neural-style.py", line 176, in <module>
    main()
  File "convert-fast-neural-style.py", line 162, in main
    unknown_layer_converter_fn=convert_instance_norm
  File "/usr/local/lib/python2.7/dist-packages/torch2coreml/_torch_converter.py", line 195, in convert
    torch_model.evaluate()
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Container.py", line 39, in evaluate
    self.applyToModules(lambda m: m.evaluate())
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Container.py", line 26, in applyToModules
    func(module)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Container.py", line 39, in <lambda>
    self.applyToModules(lambda m: m.evaluate())
TypeError: 'NoneType' object is not callable
```
is their any way through to complete the conversation

**Comment by tastyminerals** [comment]
This has been answered in #1080, please close.
