### ISSUE TITLE
Error installing Torch

### ISSUE THREAD

**Issue by samarohith** [torch/torch7#1206]
When I try to install torch using "pip install torch", I get the below error,can anyone help?

Collecting torch
  Using cached https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz
Requirement already satisfied: pyyaml in c:\users\reddy\appdata\local\programs\python\python36\lib\site-packages (from torch) (5.1.1)
Installing collected packages: torch
  Running setup.py install for torch ... error
    ERROR: Complete output from command 'c:\users\reddy\appdata\local\programs\python\python36\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\reddy\\AppData\\Local\\Temp\\pip-install-eatdnva7\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\reddy\AppData\Local\Temp\pip-record-q1pey2ec\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\reddy\AppData\Local\Temp\pip-install-eatdnva7\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "c:\users\reddy\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\reddy\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\reddy\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\reddy\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\reddy\AppData\Local\Temp\pip-install-eatdnva7\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "c:\users\reddy\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\reddy\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\reddy\AppData\Local\Temp\pip-install-eatdnva7\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command "'c:\users\reddy\appdata\local\programs\python\python36\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\reddy\\AppData\\Local\\Temp\\pip-install-eatdnva7\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\reddy\AppData\Local\Temp\pip-record-q1pey2ec\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\reddy\AppData\Local\Temp\pip-install-eatdnva7\torch\

**Comment by positron96** [comment]
I am getting this error as well, how is it fixed?

**Comment by samarohith** [comment]
I went to this link [https://pytorch.org/get-started/locally/](url)  and followed those instructions
